name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deps
      run: apt-get update && apt-get install -y libpango
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/flowtime
            asset_name: flowtime-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/flowtime.exe
            asset_name: flowtime-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/flowtime
            asset_name: flowtime-macos

    steps:
    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}
