name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y pkg-config libpango1.0-dev libgraphene-1.0-dev librust-glib-sys-dev libgtk-4-dev libadwaita-1-dev libasound2-dev portaudio19-dev build-essential ubuntustudio-audio-core librust-glib-sys-dev libglib2.0-dev --fix-missing 
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target ${{ matrix.target }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        target: ["x86_64-unknown-linux-musl", "x86_64-pc-windows-gnu"]
      max-parallel: 2

    outputs:
      binaries: ${{ steps.build.outputs.binaries }}

  publish:
    needs: build
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Publish Release
      id: publish
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ needs.build.outputs.binaries }}
        tag_name: v${{ github.ref }}
        name: Release ${{ github.ref }}
        body: ''
